# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as builder-runner
RUN microdnf install -y skopeo jq python3 python3-pip
RUN . /cachi2/cachi2.env && pip3 install /cachi2/output/deps/pip/ruamel.yaml-0.17.9.tar.gz

# Use a new stage to enable caching of the package installations for local development
FROM builder-runner as builder

COPY rh-3scale-operator/bundle-hack .
COPY rh-3scale-operator/3scale-operator/bundle/manifests /manifests/
COPY rh-3scale-operator/3scale-operator/bundle/metadata /metadata/

RUN ./update_bundle.sh

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=3scale-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL com.redhat.component="3scale-operator-bundle-container" \
      name="3scale-amp2/3scale-rhel7-operator-metadata" \
      summary="3scale operator container image prod metadata" \
      description="3scale operator container image prod metadata" \
      io.k8s.display-name="3scale operator metadata" \
      io.openshift.expose-services="" \
      io.openshift.tags="3scale, api" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY rh-3scale-operator/3scale-operator/bundle/tests/scorecard /tests/scorecard/