apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/rh-3scale?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.openshift.io/build-nudge-files: "bundle-hack/update_bundle.sh"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch  == "main" &&
      (".tekton/apicast-gateway-pull-request.yaml".pathChanged() ||
      ".tekton/apicast-gateway-push.yaml".pathChanged() ||
      "rh-apicast/***".pathChanged() ||
      "drift-cache/apicast/***".pathChanged() ||
      "rh-apicast/apicast".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: threescale
    appstudio.openshift.io/component: apicast-gateway
    pipelines.appstudio.openshift.io/type: build
  name: apicast-gateway-on-push
  namespace: 3scale-prod-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/3scale-prod-tenant/apicast-gateway:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/amd64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: rh-apicast/apicast/Containerfile
  - name: path-context
    value: rh-apicast/apicast
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  pipelineRef:
    name: build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
