apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/rh-3scale?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/threescale-operator-pull-request.yaml".pathChanged() ||
      ".tekton/threescale-operator-push.yaml".pathChanged() ||
      "rh-3scale-operator/Containerfile.3scale-operator".pathChanged() ||
      "rh-3scale-operator/3scale-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: threescale
    appstudio.openshift.io/component: threescale-operator
    pipelines.appstudio.openshift.io/type: build
  name: threescale-operator-on-pull-request
  namespace: 3scale-prod-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/3scale-prod-tenant/threescale-operator:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: rh-3scale-operator/Containerfile.3scale-operator
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      - linux/amd64
      - linux/ppc64le
      - linux/s390x
  - name: prefetch-input
    value: '{"type": "gomod", "path": "rh-3scale-operator/3scale-operator/"}'
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  pipelineRef:
    name: multi-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'