apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/rh-3scale?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # when adding filter for directory use "directory/***".pathChanged()
    # when adding filter for git submodule use "submodule".pathChanged()
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && 
      (".tekton/single-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/threescale-operator-bundle-pull-request.yaml".pathChanged() ||
      ".tekton/threescale-operator-bundle-push.yaml".pathChanged() ||
      "rh-3scale-operator/Containerfile.3scale-operator-bundle".pathChanged() ||
      "rh-3scale-operator/3scale-operator".pathChanged() ||
      "rh-3scale-operator/rpms.in.yaml".pathChanged() ||
      "rh-3scale-operator/rpms.lock.yaml".pathChanged() ||
      "rh-3scale-operator/pyproject.toml".pathChanged() ||
      "rh-3scale-operator/bundle-hack/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: threescale
    appstudio.openshift.io/component: threescale-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: threescale-operator-bundle-on-pull-request
  namespace: 3scale-prod-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/3scale-prod-tenant/threescale-operator-bundle:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: /rh-3scale-operator/Containerfile.3scale-operator-bundle
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: 
      - {"type": "rpm", "path": "rh-3scale-operator/"}
      - {"type": "pip", "path": "rh-3scale-operator/"}
  - name: prefetch-dev-package-managers-enabled
    value: "true"
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
